Repository hashicorp/terraform-provider-hcp, pull requests merged in 2023-10, with the labels that each got.

#616 Fix Packer Docs
  docs/data-sources/packer_bucket_names.md
  docs/data-sources/packer_image.md
  docs/data-sources/packer_iteration.md
  docs/guides/packer-channel-management.md
  docs/guides/packer-run-tasks-with-terraform.md
  docs/resources/packer_channel.md
  docs/resources/packer_channel_assignment.md
  templates/data-sources/packer_bucket_names.md.tmpl
  templates/data-sources/packer_image.md.tmpl
  templates/data-sources/packer_iteration.md.tmpl
  templates/guides/packer-channel-management.md.tmpl
  templates/guides/packer-run-tasks-with-terraform.md.tmpl
  templates/resources/packer_channel.md.tmpl
  templates/resources/packer_channel_assignment.md.tmpl
Labels: bug, documentation, pr/no-changelog

#615 Fix HVN Docs
  docs/data-sources/hvn.md
  docs/data-sources/hvn_peering_connection.md
  docs/data-sources/hvn_route.md
  docs/guides/hvn-route-migration-guide.md
  docs/resources/aws_network_peering.md
  docs/resources/hvn_peering_connection.md
  templates/data-sources/hvn.md.tmpl
  templates/data-sources/hvn_peering_connection.md.tmpl
  templates/data-sources/hvn_route.md.tmpl
  templates/guides/hvn-route-migration-guide.md.tmpl
  templates/resources/aws_network_peering.md.tmpl
  templates/resources/hvn_peering_connection.md.tmpl
Labels: bug, documentation, pr/no-changelog

#613 Fix Boundary Docs
  docs/data-sources/boundary_cluster.md
  docs/resources/boundary_cluster.md
  templates/data-sources/boundary_cluster.md.tmpl
  templates/resources/boundary_cluster.md.tmpl
Labels: bug, documentation, pr/no-changelog

#614 Fix Consul Docs
  docs/data-sources/consul_agent_helm_config.md
  docs/data-sources/consul_agent_kubernetes_secret.md
  docs/data-sources/consul_cluster.md
  docs/data-sources/consul_versions.md
  docs/guides/consul-federation.md
  docs/guides/consul-root-token.md
  docs/guides/consul-snapshots.md
  docs/resources/consul_snapshot.md
  templates/data-sources/consul_agent_helm_config.md.tmpl
  templates/data-sources/consul_agent_kubernetes_secret.md.tmpl
  templates/data-sources/consul_cluster.md.tmpl
  templates/data-sources/consul_versions.md.tmpl
  templates/guides/consul-federation.md.tmpl
  templates/guides/consul-root-token.md.tmpl
  templates/guides/consul-snapshots.md.tmpl
  templates/resources/consul_snapshot.md.tmpl
Labels: bug, documentation, pr/no-changelog

#620 Documentation Subcategories Formatting Fix
  .changelog/620.txt
Labels: bug, documentation

#622 Remove subcategories from Guides
  .changelog/622.txt
  docs/guides/consul-federation.md
  docs/guides/consul-root-token.md
  docs/guides/consul-snapshots.md
  docs/guides/hvn-route-migration-guide.md
  docs/guides/packer-channel-management.md
  docs/guides/packer-run-tasks-with-terraform.md
  docs/guides/vault-admin-token.md
  docs/guides/vault-performance-replication.md
  docs/guides/vault-scaling.md
  templates/guides/consul-federation.md.tmpl
  templates/guides/consul-root-token.md.tmpl
  templates/guides/consul-snapshots.md.tmpl
  templates/guides/hvn-route-migration-guide.md.tmpl
  templates/guides/packer-channel-management.md.tmpl
  templates/guides/packer-run-tasks-with-terraform.md.tmpl
  templates/guides/vault-admin-token.md.tmpl
  templates/guides/vault-performance-replication.md.tmpl
  templates/guides/vault-scaling.md.tmpl
Labels: bug, documentation

#623 Add support for multiple patch releases in a row
  .github/workflows/prerelease.yml
Labels: bug, github_actions, pr/no-changelog

#619 Return error if the vault secrets app resource is not found.
  .changelog/619.txt
  internal/provider/resource_vault_secrets_app.go
Labels: bug, go

#626 Adding TF Guides for Vault Secrets
  docs/guides/vault-secrets-data-sources.md
  docs/guides/vault-secrets-resources.md
  examples/guides/vault_secrets/datasources.tf
  examples/guides/vault_secrets/datasourcesingle.tf
  examples/guides/vault_secrets/resourceapp.tf
  examples/guides/vault_secrets/resources.tf
  templates/guides/vault-secrets-data-sources.md.tmpl
  templates/guides/vault-secrets-resources.md.tmpl
Labels: pr/no-changelog

#632 `vaultsecrets` and General Repository Housekeeping
  .github/CODEOWNERS
  go.mod
  go.sum
  internal/clients/client.go
  internal/clients/vault_secrets.go
  internal/provider/acctest/random.go
  internal/provider/acctest/setup.go
  internal/provider/acctest/test_util.go
  internal/provider/acctest/testcheck.go
  internal/provider/project_helpers.go
  internal/provider/provider.go
  internal/provider/test_helpers_test.go
  internal/provider/vaultsecrets/data_source_vault_secrets_app.go
  internal/provider/vaultsecrets/data_source_vault_secrets_app_test.go
  internal/provider/vaultsecrets/data_source_vault_secrets_secret.go
  internal/provider/vaultsecrets/data_source_vault_secrets_secret_test.go
  internal/provider/vaultsecrets/resource_vault_secrets_app.go
  internal/provider/vaultsecrets/resource_vault_secrets_app_test.go
  internal/provider/vaultsecrets/resource_vault_secrets_secret.go
  internal/provider/vaultsecrets/resource_vault_secrets_secret_test.go
Labels: dependencies, go, pr/no-changelog

#633 Move SDKv2 tests to use `terraform-plugin-test`
  internal/providersdkv2/data_source_aws_transit_gateway_attachment.go
  internal/providersdkv2/data_source_consul_agent_helm_config.go
  internal/providersdkv2/data_source_consul_agent_kubernetes_secret.go
  internal/providersdkv2/data_source_consul_cluster.go
  internal/providersdkv2/data_source_consul_versions.go
  internal/providersdkv2/data_source_hvn_route.go
  internal/providersdkv2/data_source_packer_bucket_names.go
  internal/providersdkv2/data_source_packer_bucket_names_test.go
  internal/providersdkv2/data_source_packer_image_test.go
  internal/providersdkv2/data_source_packer_iteration_test.go
  internal/providersdkv2/data_source_packer_run_task_test.go
  internal/providersdkv2/data_source_vault_cluster.go
  internal/providersdkv2/data_source_vault_plugin.go
  internal/providersdkv2/location_test.go
  internal/providersdkv2/provider.go
  internal/providersdkv2/resource_aws_network_peering.go
  internal/providersdkv2/resource_aws_network_peering_test.go
  internal/providersdkv2/resource_aws_transit_gateway_attachment.go
  internal/providersdkv2/resource_aws_transit_gateway_attachment_test.go
  internal/providersdkv2/resource_azure_peering_connection_test.go
  internal/providersdkv2/resource_boundary_cluster_test.go
  internal/providersdkv2/resource_consul_cluster.go
  internal/providersdkv2/resource_consul_cluster_root_token.go
  internal/providersdkv2/resource_consul_cluster_test.go
  internal/providersdkv2/resource_consul_snapshot.go
  internal/providersdkv2/resource_consul_snapshot_test.go
  internal/providersdkv2/resource_hvn.go
  internal/providersdkv2/resource_hvn_peering_connection_test.go
  internal/providersdkv2/resource_hvn_route.go
  internal/providersdkv2/resource_hvn_route_test.go
  internal/providersdkv2/resource_hvn_test.go
  internal/providersdkv2/resource_packer_channel_assignment_test.go
  internal/providersdkv2/resource_packer_channel_test.go
  internal/providersdkv2/resource_packer_run_task_test.go
  internal/providersdkv2/resource_vault_cluster.go
  internal/providersdkv2/resource_vault_cluster_perf_replication_test.go
  internal/providersdkv2/resource_vault_cluster_test.go
  internal/providersdkv2/resource_vault_plugin.go
  internal/providersdkv2/resource_vault_plugin_test.go
  internal/providersdkv2/test_helpers_test.go
  internal/providersdkv2/validators_test.go
Labels: go, pr/no-changelog

#646 Add codeowner for IAM resources
  .github/CODEOWNERS
Labels: pr/no-changelog

#648 Update changelog for #637 to include breaking change
  .changelog/637.txt
Labels: pr/no-changelog

#649 Network resources ownership
  .github/CODEOWNERS
Labels: pr/no-changelog

#659 Remove outdated warning
  .github/workflows/terraform_provider.yml
  README.md
Labels: documentation, pr/no-changelog
