Repository hashicorp/terraform-provider-hcp, pull requests merged in 2023-06, with the labels that each got.

#521 HPR-1177: Assigned iteration should not be forced to be null when no iteration block is present
  .changelog/521.txt
  docs/resources/packer_channel.md
  examples/resources/hcp_packer_channel/resource_assignment.tf
  internal/clients/packer.go
  internal/provider/resource_packer_channel.go
  templates/resources/packer_channel.md.tmpl
Labels: bug

#522 HCPF-704: Fix Missing/Incorrect Resource-level `project_id` Implementations
  .changelog/522.txt
  docs/data-sources/hvn_peering_connection.md
  docs/data-sources/hvn_route.md
  docs/resources/hvn_peering_connection.md
  docs/resources/hvn_route.md
  examples/data-sources/hcp_hvn_peering_connection/data-source.tf
  examples/data-sources/hcp_hvn_peering_connection/variables.tf
  internal/provider/data_source_azure_peering_connection.go
  internal/provider/data_source_consul_agent_helm_config.go
  internal/provider/data_source_consul_agent_kubernetes_secret.go
  internal/provider/data_source_hvn_peering_connection.go
  internal/provider/data_source_hvn_route.go
  internal/provider/resource_azure_peering_connection.go
  internal/provider/resource_boundary_cluster.go
  internal/provider/resource_consul_cluster_root_token.go
  internal/provider/resource_hvn_peering_connection.go
  internal/provider/resource_hvn_peering_connection_test.go
  internal/provider/resource_hvn_route.go
  internal/provider/resource_packer_channel.go
  internal/provider/resource_vault_cluster_admin_token.go
Labels: bug

#517 Update Contributor Docs and Resource-Specific Import Examples to Reflect Multi-Project Support
  .changelog/517.txt
  contributing/README.md
  contributing/checklist-resource-import.md
  contributing/checklist-resource.md
  docs/data-sources/packer_image_iteration.md
  docs/data-sources/packer_iteration.md
  docs/resources/aws_network_peering.md
  docs/resources/aws_transit_gateway_attachment.md
  docs/resources/azure_peering_connection.md
  docs/resources/boundary_cluster.md
  docs/resources/consul_cluster.md
  docs/resources/hvn.md
  docs/resources/hvn_peering_connection.md
  docs/resources/hvn_route.md
  docs/resources/packer_channel.md
  docs/resources/vault_cluster.md
  examples/resources/hcp_aws_network_peering/import.sh
  examples/resources/hcp_aws_transit_gateway_attachment/import.sh
  examples/resources/hcp_azure_peering_connection/import.sh
  examples/resources/hcp_boundary_cluster/import.sh
  examples/resources/hcp_consul_cluster/import.sh
  examples/resources/hcp_hvn/import.sh
  examples/resources/hcp_hvn_peering_connection/import.sh
  examples/resources/hcp_hvn_route/import.sh
  examples/resources/hcp_packer_channel/import.sh
  examples/resources/hcp_vault_cluster/import.sh
  internal/provider/resource_hvn_peering_connection.go
  templates/data-sources/packer_image_iteration.md.tmpl
  templates/data-sources/packer_iteration.md.tmpl
Labels: documentation

#530 [docs] Fix link to architecture image now that cloud website has moved
  docs/index.md
  templates/index.md.tmpl
Labels: documentation, pr/no-changelog

#533 HPR-1208: Fix panic when `hcp_packer_image` points to an empty channel
  .changelog/533.txt
  internal/provider/data_source_packer_image.go
  internal/provider/data_source_packer_image_iteration_test.go
  internal/provider/data_source_packer_image_test.go
  internal/provider/data_source_packer_iteration_test.go
Labels: bug

#539 Move Statuspage.io config to a dedicated file
  .github/CODEOWNERS
  internal/provider/provider.go
  internal/provider/statuspage.go
Labels: pr/no-changelog

#531 HPR-1172: Add `hcp_packer_channel_assignment` Resource
  .changelog/531.txt
  docs/data-sources/packer_image.md
  docs/data-sources/packer_image_iteration.md
  docs/data-sources/packer_iteration.md
  docs/guides/packer-channel-management.md
  docs/resources/packer_channel.md
  docs/resources/packer_channel_assignment.md
  examples/guides/packer_channel_management/assign_latest.tf
  examples/guides/packer_channel_management/main.tf
  examples/resources/hcp_packer_channel/resource_assignment.tf
  examples/resources/hcp_packer_channel/resource_using_latest_channel.tf
  examples/resources/hcp_packer_channel_assignment/import.sh
  examples/resources/hcp_packer_channel_assignment/resource.tf
  go.mod
  go.sum
  golangci-config.yml
  internal/clients/packer.go
  internal/provider/data_source_packer_image.go
  internal/provider/data_source_packer_image_iteration.go
  internal/provider/data_source_packer_image_iteration_test.go
  internal/provider/data_source_packer_iteration.go
  internal/provider/provider.go
  internal/provider/resource_packer_channel.go
  internal/provider/resource_packer_channel_assignment.go
  internal/provider/resource_packer_channel_assignment_test.go
  internal/provider/test_helpers.go
  internal/provider/test_helpers_packer_test.go
  internal/provider/test_helpers_test.go
  templates/data-sources/packer_image_iteration.md.tmpl
  templates/guides/packer-channel-management.md.tmpl
  templates/resources/packer_channel.md.tmpl
Labels: enhancement

#542 Do not swallow sdk error
  .changelog/542.txt
  internal/clients/retry_request.go
Labels: bug
