Repository hashicorp/terraform-provider-hcp, pull requests merged in 2023-09, with the labels that each got.

#600 Add missing `Sensitive: true` on `vault_secrets_secret` data source
  docs/data-sources/vault_secrets_secret.md
  internal/provider/data_source_vault_secrets_secret.go
Labels: bug, go, pr/no-changelog

#601 Push automatic prereleases back by 2 hours
  .github/workflows/prerelease.yml
Labels: bug, github_actions, pr/no-changelog

#608 Updates for a manual patch release
  CHANGELOG.md
  docs/index.md
  examples/provider/provider.tf
Labels: pr/no-changelog

#609 HPR-1286: Remove `hcp_packer_image_iteration` data source
  .changelog/609.txt
  docs/data-sources/packer_image_iteration.md
  internal/providersdkv2/data_source_packer_image_iteration.go
  internal/providersdkv2/data_source_packer_image_iteration_test.go
  internal/providersdkv2/provider.go
  internal/providersdkv2/test_helpers_packer_test.go
  templates/data-sources/packer_image_iteration.md.tmpl
Labels: go

#610 Upgrade to Go 1.20
  .changelog/610.txt
  .github/workflows/terraform_provider.yml
  .go-version
  contributing/README.md
  go.mod
Labels: enhancement, dependencies, go

#611 Grouped update of TF packages that just released Go 1.20 versions
  go.mod
  go.sum
Labels: dependencies, pr/no-changelog
