Repository hashicorp/terraform-provider-hcp, pull requests merged in 2024-04, with the labels that each got.

#804 Update waypoint docs
  docs/resources/waypoint_add_on_definition.md
  docs/resources/waypoint_application.md
  docs/resources/waypoint_application_template.md
  templates/resources/waypoint_add_on_definition.md.tmpl
  templates/resources/waypoint_application.md.tmpl
  templates/resources/waypoint_application_template.md.tmpl
Labels: documentation, pr/no-changelog

#806 Update AddOn schema/model to include project_id, organization_id
  internal/provider/waypoint/resource_waypoint_add_on.go
Labels: pr/no-changelog

#811 update tests to use real tf no-code modules
  internal/provider/waypoint/resource_waypoint_add_on_definition_test.go
  internal/provider/waypoint/resource_waypoint_application_template_test.go
Labels: pr/no-changelog, waypoint

#809 Use templates for Waypoint data-source docs
  docs/data-sources/waypoint_add_on.md
  docs/data-sources/waypoint_add_on_definition.md
  docs/data-sources/waypoint_application.md
  docs/data-sources/waypoint_application_template.md
  templates/data-sources/waypoint_add_on.md.tmpl
  templates/data-sources/waypoint_add_on_definition.md.tmpl
  templates/data-sources/waypoint_application.md.tmpl
  templates/data-sources/waypoint_application_template.md.tmpl
Labels: pr/no-changelog

#824 Waypoint: Temporary fix for panic due to api change
  internal/provider/waypoint/resource_waypoint_tfc_config_test.go
Labels: pr/no-changelog

#823 Bump hcp-sdk-go to 0.93.0, address Waypoint TFCConfig bug
  go.mod
  go.sum
  internal/provider/waypoint/resource_waypoint_tfc_config_test.go
Labels: pr/no-changelog

#816 Waypoint: Add variable options to template resource
  .changelog/816.txt
  docs/data-sources/waypoint_application_template.md
  docs/resources/waypoint_application_template.md
  internal/provider/waypoint/data_source_waypoint_application_template.go
  internal/provider/waypoint/data_source_waypoint_application_template_test.go
  internal/provider/waypoint/resource_waypoint_application_template.go
  internal/provider/waypoint/resource_waypoint_application_template_test.go
Labels: waypoint

#827 hvs code ownership fix
  .github/CODEOWNERS
Labels: pr/no-changelog
